line1= " Welcome to our school.\n "
line2= "\n "
line3= "\n "
line4= "\n "
line5= "\n "
line6= "\n"
line7= "\n"
line8= "\n"
line9= "\n"
line10= "Welcome to the first floor\n"
print(line1 + line2 + line3 + line4 + line5 + line6 + line7 + line8 + line9 + line10)